# Generated by Django 6.0.2 on 2026-02-04 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Specialization', models.CharField(max_length=255)),
                ('Phone_Number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1)),
                ('Date', models.DateField()),
                ('Concerns', models.TextField()),
                ('Phone_Number', models.BigIntegerField()),
                ('is_booked', models.CharField(default='Booked', max_length=200)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.doctor')),
                ('Slot_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.doctor')),
                ('Patient_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.patient')),
                ('Slot_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.slot')),
            ],
        ),
    ]
