# Generated by Django 6.0.2 on 2026-02-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Doctor_Id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Slot_Id',
        ),
    ]
