# Generated by Django 6.0.2 on 2026-02-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_remove_patient_doctor_id_remove_patient_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
