# Generated by Django 6.0.2 on 2026-02-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_alter_patient_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1),
        ),
    ]
