# Generated by Django 6.0.2 on 2026-02-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='Id',
            new_name='Slot_Id',
        ),
    ]
