# Generated by Django 6.0.2 on 2026-02-05 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_rename_id_slot_slot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_booked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
