# Generated by Django 6.0.2 on 2026-02-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookings',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='slot',
            table='slot',
        ),
    ]
