# Generated by Django 6.0.2 on 2026-02-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_alter_bookings_table_alter_doctor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
        migrations.AlterModelTable(
            name='slot',
            table=None,
        ),
    ]
